/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tic.tac.toe;
import java.awt.event.WindowEvent;
import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public boolean isX=true;
    public boolean hide=true;
    public String btn1="A", btn2="B", btn3="C", btn4="D", btn5="E", btn6="F", btn7="G", btn8="H", btn9="I", win;
    public MainWindow() {
        initComponents();
        show_bg(hide);
        jButtonpvp.setVisible(false);
        jButtonpvc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jButtons = new javax.swing.JButton();
        jButtonpvp = new javax.swing.JButton();
        jButtonpvc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();

        jDialog1.setBackground(java.awt.Color.darkGray);
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 250, 100));
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setFont(new java.awt.Font("Adobe Arabic", 1, 18)); // NOI18N
        jDialog1.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC TAC TOE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtons.setLabel("Start");
        jButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonpvp.setLabel("Player Vs Player");
        jButtonpvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpvpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonpvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jButtonpvc.setLabel("Player Vs Computer");
        jButtonpvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpvcActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonpvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setName("bla"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 120, -1, -1));

        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 120, -1, -1));

        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 120, -1, -1));

        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 226, -1, -1));

        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 226, -1, -1));

        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 226, -1, -1));

        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 332, -1, -1));

        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 332, -1, -1));

        jButton9.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 332, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("EXIT");
        exit.setName("exit"); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CheckWinLine(){
     if(btn1.equals(btn2) && btn1.equals(btn3)) {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
//============ Trebuie sa renuntam la optiunea de start new game =>nu va mai fi nevoie de o alta fereastra pt un nou joc!
           //=================================================== => toata aplicatia va avea o singura fereastra!
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow();
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);

            }
//============================ De scos acest if din else-ul de mai sus peste tot in cele 3 functii de verificare
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                } 
//=====================================
            done();
          }
     if(btn4.equals(btn5) && btn4.equals(btn6)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
        }
        
        if(btn7.equals(btn8) && btn7.equals(btn9)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();    
        }  
    }
    
    public void CheckWinCol(){
      
        if(btn1.equals(btn4) && btn1.equals(btn7)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
        }
        if(btn2.equals(btn5) && btn2.equals(btn8)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
        }               
        if(btn3.equals(btn6) && btn3.equals(btn9)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
        }     
    }
    
    public void CheckWinDiag(){
    
        if(btn1.equals(btn5) && btn1.equals(btn9)) 
       {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
       } 
 
        if(btn3.equals(btn5) && btn3.equals(btn7)) 
        {
            if (!isX)
            {
             win =  "Player one wins!";   
            }
            else 
            {
             win = "Player two wins!";
            }
           Object[] options = { "Start a new game!", "Menu", "Exit"};
           jOptionPane1.showMessageDialog(rootPane, win);
           int option =   jOptionPane1.showOptionDialog(rootPane, "Do you want to start a new game?", "Choose an option:", jOptionPane1.YES_NO_CANCEL_OPTION, jOptionPane1.QUESTION_MESSAGE, null, options, options[2]);
            if( option == jOptionPane1.YES_OPTION)
            {
                  JFrame frame = new MainWindow(); 
                  frame.setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE); 
                  frame.setVisible(true);
            }
            else {
                  show_bg(hide);
                  jButtons.setEnabled(true);
                if(option == jOptionPane1.CANCEL_OPTION) {
               WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);         
                }
                else {
                }
            }
            done();
        } 
    }
    
    public void show_bg(boolean x)
    {
        if(x==true)
        {
            jButton1.setEnabled(false); jButton1.setVisible(false);
            jButton2.setEnabled(false); jButton2.setVisible(false);
            jButton3.setEnabled(false); jButton3.setVisible(false);
            jButton4.setEnabled(false); jButton4.setVisible(false);
            jButton5.setEnabled(false); jButton5.setVisible(false);
            jButton6.setEnabled(false); jButton6.setVisible(false);
            jButton7.setEnabled(false); jButton7.setVisible(false);
            jButton8.setEnabled(false); jButton8.setVisible(false);
            jButton9.setEnabled(false); jButton9.setVisible(false);
            hide=false;
        }
        else
        {
            jButton1.setEnabled(true); jButton1.setVisible(true);
            jButton2.setEnabled(true); jButton2.setVisible(true);
            jButton3.setEnabled(true); jButton3.setVisible(true);
            jButton4.setEnabled(true); jButton4.setVisible(true);
            jButton5.setEnabled(true); jButton5.setVisible(true);
            jButton6.setEnabled(true); jButton6.setVisible(true);
            jButton7.setEnabled(true); jButton7.setVisible(true);
            jButton8.setEnabled(true); jButton8.setVisible(true);
            jButton9.setEnabled(true); jButton9.setVisible(true);
            hide=true;
        }
    }
      
    
    private void done(){
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isX)
        {
            jButton1.setText("X");
            isX=false;
        }
        else
        {
            jButton1.setText("O");
            isX=true;
        }
        jButton1.setEnabled(false);
        
        btn1 = jButton1.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
       
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(isX)
        {
            jButton2.setText("X");
            isX=false;
        }
        else
        {
            jButton2.setText("O");
            isX=true;
        }
        jButton2.setEnabled(false);
        btn2 = jButton2.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(isX)
        {
            jButton3.setText("X");
            isX=false;
        }
        else
        {
            jButton3.setText("O");
            isX=true;
        }
        jButton3.setEnabled(false);
        btn3 = jButton3.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if(isX)
        {
            jButton4.setText("X");
            isX=false;
        }
        else
        {
            jButton4.setText("O");
            isX=true;
        }
        jButton4.setEnabled(false);
        btn4 = jButton4.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(isX)
        {
            jButton5.setText("X");
            isX=false;
        }
        else
        {
            jButton5.setText("O");
            isX=true;
        }
        jButton5.setEnabled(false);
        btn5 = jButton5.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(isX)
        {
            jButton6.setText("X");
            isX=false;
        }
        else
        {
            jButton6.setText("O");
            isX=true;
        }
        jButton6.setEnabled(false);
        btn6 = jButton6.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(isX)
        {
            jButton7.setText("X");
            isX=false;
        }
        else
        {
            jButton7.setText("O");
            isX=true;
        }
        jButton7.setEnabled(false);
        btn7 = jButton7.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         if(isX)
        {
            jButton8.setText("X");
            isX=false;
        }
        else
        {
            jButton8.setText("O");
            isX=true;
        }
        jButton8.setEnabled(false);
        btn8 = jButton8.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(isX)
        {
            jButton9.setText("X");
            isX=false;
        }
        else
        {
            jButton9.setText("O");
            isX=true;
        }
        jButton9.setEnabled(false);
        btn9 = jButton9.getText();
        CheckWinLine();
        CheckWinCol();
        CheckWinDiag();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsActionPerformed
        jButtons.setEnabled(false);
        jButtonpvp.setVisible(true);
        jButtonpvc.setVisible(true);
        jButtonpvp.setEnabled(true);
        jButtonpvc.setEnabled(true);
    }//GEN-LAST:event_jButtonsActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButtonpvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpvpActionPerformed
        show_bg(hide);
        jButtons.setEnabled(false);
        jButtonpvp.setEnabled(false);
        jButtonpvc.setEnabled(false);
    }//GEN-LAST:event_jButtonpvpActionPerformed

    private void jButtonpvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpvcActionPerformed
        show_bg(hide);
        jButtons.setEnabled(false);
        jButtonpvp.setEnabled(false);
        jButtonpvc.setEnabled(false);
    }//GEN-LAST:event_jButtonpvcActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	       this.dispatchEvent(windowClosing);
    }//GEN-LAST:event_exitActionPerformed
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonpvc;
    private javax.swing.JButton jButtonpvp;
    private javax.swing.JButton jButtons;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}